name: build-release

on:
  push:
    branch: [feature/**]
  repository_dispatch:
    types: [build-release]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download s2i
        run: curl -L https://github.com/openshift/source-to-image/releases/download/v1.3.0/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz -o $HOME/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz
      - name: Extract s2i
        run: tar xvf $HOME/source-to-image*.gz -C $HOME
      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Get latest Sakuli version number
        run: echo "::set-env name=SAKULI_VERSION::$(node -pe 'JSON.parse(process.argv[1])[0].name' "$(curl -s https://api.github.com/repos/sakuli/sakuli/tags)" | cut -c 2-6)"
      - name: Build, test and release s2i images
        run: |
          export PATH=$PATH:$HOME
          make build test prepare-release BASE_IMAGE=sakuli BASE_IMAGE_VERSION=${SAKULI_VERSION} IMAGE_NAME=taconsol/sakuli-s2i TAG_VERSION=${SAKULI_VERSION}
          make build test prepare-release BASE_IMAGE=sakuli-remote-connection BASE_IMAGE_VERSION=${SAKULI_VERSION} IMAGE_NAME=taconsol/sakuli-s2i-remote-connection TAG_VERSION=${SAKULI_VERSION}
