name: build-release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download s2i
        run: curl -L https://github.com/openshift/source-to-image/releases/download/v1.3.0/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz -o $HOME/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz
      - name: Extract s2i
        run: tar xvf $HOME/source-to-image*.gz -C $HOME
      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build, test and release s2i images
        run: |
          echo "SAKULI_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          export PATH=$PATH:$HOME
          make build test prepare-release release BASE_IMAGE=sakuli BASE_IMAGE_VERSION=${SAKULI_VERSION} IMAGE_NAME=sakuli-s2i TAG_VERSION=${SAKULI_VERSION}
          make build test prepare-release release BASE_IMAGE=sakuli-remote-connection BASE_IMAGE_VERSION=${SAKULI_VERSION} IMAGE_NAME=sakuli-s2i-remote-connection TAG_VERSION=${SAKULI_VERSION}
